# Here you can select the language
# Currently supported languages
# - English (en.yml)
# - Czech/čeština (cs.yml)
# - Custom translation - you can edit the custom.yml into any language you want (custom.yml)
# Put the language file name below (in the parentheses)
# Help by translating the plugin to other languages here: https://crowdin.com/project/fastertp
language: 'en.yml'

rtp-settings:
  max-attempts: 30

cooldown:
  enabled: true
  seconds: 600

economy:
  enabled: false
  price: 100.0

warmup:
  enabled: true
  seconds: 5