# Here you can select the language
# Currently supported languages
# - English (en.yml)
# - Czech/čeština (cs.yml)
# - Custom translation - you can edit the custom.yml into any language you want (custom.yml)
# Put the language file name below (in the parentheses)
# Help by translating the plugin to other languages here: https://crowdin.com/project/fastertp
language: 'en.yml'

rtp-settings:
  # This is the max number of times the plugin will try to find a safe location
  # Recommended: 30
  max-attempts: 30
  # Min: 0 Max: 16
  chunk-pregen-radius: 4
  bad-blocks:
    - LAVA
    - WATER
    - MAGMA_BLOCK
    - CACTUS
  # You can edit the messages and titles in the language files
  before-generation:
    message: true
  before-teleport:
    title: true
  after-teleport:
    message: true

cooldown:
  enabled: true
  seconds: 600

economy:
  enabled: false
  price: 100.0

warmup:
  enabled: true
  seconds: 5

# Don't change this
config-version: 1.0.0